services:
  backend:
    command:
      [
        "python",
        "-m",
        "uvicorn",
        "mbta.asgi:application",
        "--host",
        "0.0.0.0",
        "--port",
        "8000",
        "--reload",
      ]
    working_dir: /app/backend/mbta-server
    volumes:
      - ./backend:/app/backend

  backend-worker:
    command: ["python", "manage.py", "mbta_alerts_worker"]
    working_dir: /app/backend/mbta-server
    volumes:
      - ./backend:/app/backend

  frontend:
    command: ["npm", "run", "dev", "--", "--hostname", "0.0.0.0", "--port", "3000"]
    environment:
      WATCHPACK_POLLING: "true"
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
